# Generated by Django 6.0.6 on 2026-06-09 19:21
# Pega as alterações do meu model e aplica no banco de dados

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
