# Generated by Django 6.0.6 on 2026-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
