# Generated by Django 6.0.6 on 2026-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
